version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: econom32_postgres
    environment:
      POSTGRES_DB: econom32_new
      POSTGRES_USER: econom32_user
      POSTGRES_PASSWORD: econom32_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - econom32_network
    restart: unless-stopped

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: econom32_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - econom32_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # MinIO для хранения файлов (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: econom32_minio
    environment:
      MINIO_ROOT_USER: econom32_minio
      MINIO_ROOT_PASSWORD: econom32_minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - econom32_network
    restart: unless-stopped
    command: server /data --console-address ":9001"

  # ClamAV антивирус для проверки файлов
  clamav:
    image: clamav/clamav:latest
    container_name: econom32_clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    networks:
      - econom32_network
    restart: unless-stopped
    environment:
      CLAMAV_NO_FRESHCLAMD: "false"

  # Nginx для reverse proxy (будет настроен позже)
  nginx:
    image: nginx:alpine
    container_name: econom32_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    networks:
      - econom32_network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio

  # Adminer для управления PostgreSQL через веб-интерфейс
  adminer:
    image: adminer:latest
    container_name: econom32_adminer
    ports:
      - "8080:8080"
    networks:
      - econom32_network
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  # Prometheus для мониторинга
  prometheus:
    image: prom/prometheus:latest
    container_name: econom32_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - econom32_network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  # Grafana для визуализации метрик
  grafana:
    image: grafana/grafana:latest
    container_name: econom32_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - econom32_network
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"

volumes:
  postgres_data:
  redis_data:
  minio_data:
  clamav_data:
  prometheus_data:
  grafana_data:

networks:
  econom32_network:
    driver: bridge