# Упрощенная конфигурация AlertManager

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@econom32.ru'

# Маршрутизация алертов
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

# Получатели уведомлений
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true